### ISSUE TITLE
Recipes removed via CraftTweaker or a datapack still show in JEI.

### ISSUE THREAD

**Issue by zachsai** [MarkusBordihn/BOs-Material-Elements#3]
Recipes removed via CraftTweaker or a datapack still show in JEI.

version: 2.6.0

**Comment by MarkusBordihn** [comment]
Thanks for the report, but unfortunately this is by design by CraftTweaker.

To hide items in CraftTweaker and JEI you need to additional use JEITweaker, see:
https://www.curseforge.com/minecraft/mc-mods/jeitweaker
