### ISSUE TITLE
Unable to craft Material Elements - Iron Cube Frame

### ISSUE THREAD

**Issue by joy20man** [MarkusBordihn/BOs-Material-Elements#4]
**Describe the bug**
I have a modpack which includes both Material Elements and Immersive Engineering. When crafting an iron rod the crafting table will only give me the immersive engineering iron rod. The crafting recipe for the Iron Cube Frame and Iron Cube Glass Frame both do not recognize the iron rod from immersive engineering as a valid crafting element.

**To Reproduce**

**Expected behavior**
I expect either be able to select which type of iron rod I want to craft and/or be able to craft both of the Iron Cube Frame and Iron Cube Glass Frame recipes using either type of iron rod.

**Screenshots**
See Below

**Debugging**
N/A

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
Yes. See screenshot below

**Additional context**
I did find some rods in an chest that were from material elements and immersive engineering recognized them as being the same as the rods of the same metal needed for a crafting recipe.

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/972402/173974543-99248a1a-6cdf-424e-a1b6-f79b0a346c3a.png">

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. I will release an updated version which fix this issue and adds further compatibility with Immersive Engineering.

You could use Polymorph in the mean time, which solves such recipe issues for all mods:
https://www.curseforge.com/minecraft/mc-mods/polymorph
